#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
rebuild_index.py — 从 cache/*.json + cache/*.md 重建 references/

用法:
  py -3.12 scripts/rebuild_index.py

效果:
  - 按 URL 去重(保留最完整的)
  - 合并 flink-website-zh 到 flink-website
  - 重新分类版本(release-X.Y → stable/lts/old)
  - 重建 tag_index / version_map / summary.md

适用场景:
  - build.py --flush-every 中断后,从 cache 恢复
  - 重新分类 catalog 但不重新爬
"""
from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from pathlib import Path
from urllib.parse import urlparse

CACHE_DIR = Path(__file__).resolve().parent / "../cache"
OUTPUT_DIR = Path(__file__).resolve().parent / "../references"

RELEASE_MAP = {
    "flink-docs-stable":      "stable",
    "flink-docs-lts":         "lts",
    "flink-docs-master":      "master",
    "flink-docs-release-2.3": "stable",
    "flink-docs-release-2.2": "stable-old",
    "flink-docs-release-2.1": "stable-old",
    "flink-docs-release-2.0": "stable-old",
    "flink-docs-release-1.20": "lts-old",
    "flink-docs-release-1.19": "old",
    "flink-docs-release-1.18": "old",
    "flink-cdc-docs-stable":   "stable",
    "flink-cdc-docs-master":   "master",
    "flink-kubernetes-operator-docs-stable": "stable",
    "flink-kubernetes-operator-docs-main":   "master",
    "flink-agents-docs-latest": "agents-latest",
    "flink-agents-docs-main":   "master",
    "flink-ml-docs-stable":     "stable",
    "flink-ml-docs-master":     "master",
    "flink-statefun-docs-stable": "stable",
    "flink-statefun-docs-master": "master",
}


def classify_subproject(url: str) -> str:
    if "flink-cdc-docs" in url:
        return "flink-cdc"
    if "flink-kubernetes-operator-docs" in url:
        return "flink-k8s-operator"
    if "flink-agents-docs" in url:
        return "flink-agents"
    if "flink-ml-docs" in url:
        return "flink-ml"
    if "flink-statefun-docs" in url:
        return "flink-statefun"
    if "flink-docs" in url:
        return "flink-core"
    return "flink-website"  # flink.apache.org 主站


def classify_version(url: str) -> str:
    for path, ver in RELEASE_MAP.items():
        if path in url:
            return ver
    return "main"


def classify_type(url: str) -> str:
    p = urlparse(url).path
    if p.endswith("/sitemap.xml") or "sitemap" in p:
        return "sitemap"
    if "/posts/" in p and p != "/posts/" and p != "/posts":
        return "blog"
    if "/downloads/" in p and p != "/downloads/":
        return "download"
    if "/api/" in p:
        return "api-reference"
    if p == "/" or p == "/zh/":
        return "index"
    if any(seg in p for seg in ("/concepts/", "/dev/", "/ops/", "/learn-flink/", "/try-flink",
                                  "/connectors/", "/deployment/")):
        return "docs-page"
    return "page"


def detect_lang(url: str) -> str:
    p = urlparse(url).path
    return "zh" if "/zh/" in p or p == "/zh" else "en"


def repair_page(p: dict) -> dict:
    """修复单条 page 记录(分类 + 补字段)。"""
    url = p.get("url", "")
    if not url:
        return p
    # 合并 flink-website-zh 到 flink-website(lang 字段独立区分)
    sp = p.get("subproject") or classify_subproject(url)
    if sp == "flink-website-zh":
        sp = "flink-website"
    p["subproject"] = sp
    p["version"] = p.get("version") or classify_version(url)
    p["type"] = p.get("type") or classify_type(url)
    p["lang"] = p.get("lang") or detect_lang(url)
    p.setdefault("tags", [])
    p.setdefault("summary", "")
    p.setdefault("title", "")
    return p


def render_summary(pages: list[dict]) -> str:
    lines = [
        "# Flink Official Docs — Page Summaries",
        "",
        "> Generated by rebuild_index.py from cache.",
        "> Format: `- **[<type>]** [<title>](<url>) — <summary>`",
        "",
    ]
    pages_sorted = sorted(pages, key=lambda p: (p.get("subproject",""), p.get("version",""), p.get("url","")))
    last_group = None
    for p in pages_sorted:
        grp = f"{p.get('subproject','')} / {p.get('version','')} / {p.get('lang','')}"
        if grp != last_group:
            lines.append("")
            lines.append(f"## `{grp}`")
            lines.append("")
            last_group = grp
        url = p.get("url", "")
        title = (p.get("title") or "(no title)")[:100]
        summary = (p.get("summary") or "").replace("\n"," ").strip()[:200] or "(no summary)"
        tags = " ".join(f"#{t}" for t in (p.get("tags") or [])[:5])
        line = f"- **[{p.get('type','')}]** [{title}]({url}) — {summary}"
        if tags:
            line += f"  \n  {tags}"
        lines.append(line)
    return "\n".join(lines) + "\n"


def main() -> int:
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    raw = []
    for meta_path in CACHE_DIR.glob("*.json"):
        try:
            m = json.loads(meta_path.read_text(encoding="utf-8"))
            if m.get("url"):
                raw.append(m)
        except Exception:
            continue

    print(f"loaded {len(raw)} cached pages")

    # 去重(URL);合并时保留更完整的
    seen: dict[str, dict] = {}
    for p in raw:
        url = p["url"]
        if url not in seen:
            seen[url] = p
        else:
            cur = seen[url]
            cur_score = sum([bool(cur.get("summary")), bool(cur.get("type")), len(cur.get("tags") or [])])
            new_score = sum([bool(p.get("summary")), bool(p.get("type")), len(p.get("tags") or [])])
            if new_score > cur_score:
                seen[url] = p

    pages = [repair_page(p) for p in seen.values()]
    print(f"after dedup: {len(pages)} unique pages")

    # 写 catalog
    (OUTPUT_DIR / "catalog.json").write_text(
        json.dumps(pages, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    # tag_index
    tag_index: dict = defaultdict(list)
    for p in pages:
        url = p["url"]
        for t in (p.get("tags") or []) + [p.get("type"), p.get("subproject"), p.get("version"), p.get("lang")]:
            if t and url not in tag_index[t]:
                tag_index[t].append(url)
    (OUTPUT_DIR / "tag_index.json").write_text(
        json.dumps(dict(tag_index), ensure_ascii=False, indent=2), encoding="utf-8"
    )

    # version_map(已知稳定根 + 从子项目 / 根路径推断)
    version_map = {
        "stable-flink-core":      "https://nightlies.apache.org/flink/flink-docs-stable/",
        "lts-flink-core":         "https://nightlies.apache.org/flink/flink-docs-lts/",
        "master-flink-core":      "https://nightlies.apache.org/flink/flink-docs-master/",
        "stable-flink-cdc":       "https://nightlies.apache.org/flink/flink-cdc-docs-stable/",
        "stable-flink-k8s-operator": "https://nightlies.apache.org/flink/flink-kubernetes-operator-docs-stable/",
        "stable-flink-ml":        "https://nightlies.apache.org/flink/flink-ml-docs-stable/",
        "stable-flink-statefun":  "https://nightlies.apache.org/flink/flink-statefun-docs-stable/",
        "agents-latest-flink-agents": "https://nightlies.apache.org/flink/flink-agents-docs-latest/",
    }
    (OUTPUT_DIR / "version_map.json").write_text(
        json.dumps(version_map, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    # summary
    (OUTPUT_DIR / "summary.md").write_text(render_summary(pages), encoding="utf-8")

    # 统计
    from collections import Counter
    print(f"version_map: {len(version_map)} entries")
    print(f"tag_index:   {len(tag_index)} tags")
    print()
    print("distribution:")
    for k, v in sorted(Counter(p.get("subproject","") for p in pages).items()):
        print(f"  {k:20s} {v}")
    print()
    print("final state:")
    for f in ("catalog.json", "summary.md", "tag_index.json", "version_map.json"):
        p = OUTPUT_DIR / f
        if p.exists():
            print(f"  {f}: {p.stat().st_size/1024:.1f} KB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
